name: presubmit tests
on: [pull_request]
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: cd frontend && npm install
      - run: cd frontend && npm install yarn
      - run: make test-frontend
